server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;


    location / {
        # Si le fichier demandé n'existe pas, on renvoie vers index.html (pour le routage SPA)
        try_files $uri $uri/ /index.html;
    }

    # Mise en cache optimale des assets compilés par Vite (images, js, css)
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
