spring.application.name=task-manager
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/todo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
# Indique à Hibernate de mettre à jour le schéma (crée la table si elle n'existe pas)
spring.jpa.hibernate.ddl-auto=update
# Affiche les requêtes SQL générées dans la console (très utile pour observer la création)
spring.jpa.show-sql=true
